### ISSUE TITLE
Problems when trying to connect to same server IRC twice

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub#205]
As mentioned in https://github.com/67P/hyperchannel/pull/73#issuecomment-277054580, there seem to be some issues when trying to connect to the same IRC server twice.

In that case, I don't get connected at all, but the client doesn't seem to get notified about any problems.

When starting Sockethub with `DEBUG=*` I can see some weird behavior:

```
  sockethub-platform-irc received quit { nickname: 'hyper_galfert',
  username: '~hyper_gal',
  hostname: 'ip5f5ae372.dynamic.kabel-deutschland.de',
  message: 'Client Quit',
  time: 2017-02-03T10:40:46.922Z,
  raw: ':hyper_galfert!~hyper_gal@ip5f5ae372.dynamic.kabel-deutschland.de QUIT :Client Quit' } +9s
  sockethub:worker:qsNHZ36E3SdcpoHvAAAA:irc:module quit { nickname: 'hyper_galfert',
  username: '~hyper_gal',
  hostname: 'ip5f5ae372.dynamic.kabel-deutschland.de',
  message: 'Client Quit',
  time: 2017-02-03T10:40:46.922Z,
  raw: ':hyper_galfert!~hyper_gal@ip5f5ae372.dynamic.kabel-deutschland.de QUIT :Client Quit' } +1ms
  socket.io:client writing packet {"type":2,"data":["message",{"@type":"leave","actor":{"@type":"person","@id":"irc://hyper_galfert@irc.freenode.net","displayName":"hyper_galfert"},"target":{"@type":"room","@id":"irc://irc.freenode.net/undefined"},"object":{"@type":"message","content":"user has quit"},"published":"2017-02-03T10:40:46.922Z","platform":"irc"}],"nsp":"/"} +9s
  socket.io-parser encoding packet {"type":2,"data":["message",{"@type":"leave","actor":{"@type":"person","@id":"irc://hyper_galfert@irc.freenode.net","displayName":"hyper_galfert"},"target":{"@type":"room","@id":"irc://irc.freenode.net/undefined"},"object":{"@type":"message","content":"user has quit"},"published":"2017-02-03T10:40:46.922Z","platform":"irc"}],"nsp":"/"} +9s
  socket.io-parser encoded {"type":2,"data":["message",{"@type":"leave","actor":{"@type":"person","@id":"irc://hyper_galfert@irc.freenode.net","displayName":"hyper_galfert"},"target":{"@type":"room","@id":"irc://irc.freenode.net/undefined"},"object":{"@type":"message","content":"user has quit"},"published":"2017-02-03T10:40:46.922Z","platform":"irc"}],"nsp":"/"} as 2["message",{"@type":"leave","actor":{"@type":"person","@id":"irc://hyper_galfert@irc.freenode.net","displayName":"hyper_galfert"},"target":{"@type":"room","@id":"irc://irc.freenode.net/undefined"},"object":{"@type":"message","content":"user has quit"},"published":"2017-02-03T10:40:46.922Z","platform":"irc"}] +1ms
  engine:socket sending packet "message" (2["message",{"@type":"leave","actor":{"@type":"person","@id":"irc://hyper_galfert@irc.freenode.net","displayName":"hyper_galfert"},"target":{"@type":"room","@id":"irc://irc.freenode.net/undefined"},"object":{"@type":"message","content":"user has quit"},"published":"2017-02-03T10:40:46.922Z","platform":"irc"}]) +9s
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "42["message",{"@type":"leave","actor":{"@type":"person","@id":"irc://hyper_galfert@irc.freenode.net","displayName":"hyper_galfert"},"target":{"@type":"room","@id":"irc://irc.freenode.net/undefined"},"object":{"@type":"message","content":"user has quit"},"published":"2017-02-03T10:40:46.922Z","platform":"irc"}]" +0ms
  sockethub-platform-irc Unprocessed message [irc://hyper_galfert@irc.freenode.net]:  { time: 2017-02-03T10:40:46.931Z,
  reconnecting: false,
  attempts: 1 } +8ms
  engine:ws received "2" +213ms
  engine:socket packet +0ms
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "3" +0ms
  engine:ws received "2" +25s
  engine:socket packet +0ms
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "3" +0ms
  sockethub-platform-irc isConnected() called, returning: false +36s
  connection-manager client irc://hyper_galfert@irc.freenode.net is disconnected, but reference count: 1, reconnecting... +0ms
```

After leaving the client open for a while, Sockethub even crashes at some point:

```
  sockethub:worker:qsNHZ36E3SdcpoHvAAAA:irc:module disconnect for irc://hyper_galfert@irc.freenode.net +1ms
  sockethub:worker:qsNHZ36E3SdcpoHvAAAA:irc caught error:  Error: TypeError: Cannot read property 'disconnect' of undefined
    at Timeout._onTimeout (/Users/galfert/code/active/kosmos/sockethub/node_modules/connection-manager/lib/manager.js:402:17)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5) +3ms
  connection-manager removing reference: qsNHZ36E3SdcpoHvAAAA from client irc://hyper_galfert@irc.freenode.net +0ms
  connection-manager queuing client for possible disconnect. +0ms
  connection-manager removing reference: qsNHZ36E3SdcpoHvAAAA from client irc://hyper_galfert@irc.freenode.net +1ms
  connection-manager queuing client for possible disconnect. +0ms
  sockethub:worker:qsNHZ36E3SdcpoHvAAAA:irc disposing of domain +0ms
  connection-manager ending client irc://hyper_galfert@irc.freenode.net +5s
  connection-manager references:  [] +0ms
  sockethub:worker:qsNHZ36E3SdcpoHvAAAA:irc:module disconnect for irc://hyper_galfert@irc.freenode.net +0ms

UNCAUGHT EXCEPTION - something horrible has happened!

Error: TypeError: Cannot read property 'disconnect' of undefined
    at Timeout._onTimeout (/Users/galfert/code/active/kosmos/sockethub/node_modules/connection-manager/lib/manager.js:402:17)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

I created a branch in Hyperchannel to reproduce these errors. It's at https://github.com/67P/hyperchannel/tree/sockethub_bug.

After starting Hyperchannel, just go to `http://localhost:4200/sockethub-bug`.

**Comment by skddc** [comment]
I see that crash as well sometimes. I think it's in the same context.

**Comment by silverbucket** [comment]
Odd I tried this on the branch `sockethub_bug` and don't get the same behavior.

By default, connection-manager shares the same connection when more than one connect request (join) is received. Which is what it ended up doing (got 3 join requests, but only the first one was completed, the other 2 just used the established connection from the first).

If you use `DEBUG=sockethub*` the debug output is more concise (and less chatty) and you could paste the entire output from connect until the error occurs, that might help to get a better picture of what is happening. I've tried 4-5 times on my system and haven't been able to reproduce the error.

Working on improving the startup process because I did notice some kind of issue with validation and the `kue` process.

**Comment by skddc** [comment]
I think this happened with Sockethub running locally, while changing networks and being offline in between. So this would likely be solved by implementing PING and thus improving IRC server connectivity handling, as discussed in https://github.com/67P/hyperchannel/issues/77

**Comment by silverbucket** [comment]
No I think the PING issue is different, this has to do with some sort of race condition when two connects come in, Sockethub doesn't like it. I'm now able to recreate the issue but still not sure what's going on, it just looks like the connect job never gets created for the worker to process, so the IRC platform is never even initialized.

**Comment by silverbucket** [comment]
I think this might have been due to an upstream issue with socket.io, updating the deps and trying again I'm not able to recreate this problem. Can someone confirm this? If so we can close the issue.
